### ISSUE TITLE
Everything is prefixed by 'pdf'

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/reader#20]
From my personal observation of the code everything a lot of class names, component names, react props and object properties (in state) are prefixed with a _pdf_. I am wondering why?

Sometimes it seems to be unnecessary and looks strange, for example _recommender section_ is just an instance of CORE Recommender and it should not be a _PDFRecommender_.

On other side are props like `pdfEventBus` with corresponding classes like `PDFEventBus` which I might no completely understand.

**Comment by Joozty** [comment]
I tried to add prefix `PDF` to everything related to PDF. There is no big reason for it maybe I just wanted to keep consistency with [PDF.js](https://github.com/mozilla/pdf.js/blob/master/web/app.js#L91-L117).

Basically the reader is divided into few sections/components prefixed with `PDF`. The names explain what they take care of. 

The most important are:
- **PDFLoader** - responsible for loading PDF document (not rendering)
- **PDFViewer** - Takes the loaded document and renders pages - after it's rendered some events are fired. 

Regarding the props names. Yeah, I do agree indeed and I will change it. :)

Regarding recommender - I think it's part of the reader and hence the prefix should stay. But it's questionable and I can rename it if you insist.

And the last but not least - `pdfEventBus` This is event bus used for firing and subscribing to events fired within PDF.js. Events like `pagesRendered`, `pageNumberChange`.

I believe it is much cleaner now. 🙂 

The summary is that I am open to suggestion for project structure and maybe we could get rid of those prefixes indeed.

**Comment by Joozty** [comment]
@viktor-yakubiv This issue is quite old. We should somehow solve it. Otherwise, it stays here forever.

I do agree `pdf-recommender` should be renamed to just `recommender`. Do you see anything else which should be renamed? I must confess that I have started to like the idea about renaming everything, i.e. get rid of `pdf` prefixes almost everywhere. WDYT?

**Comment by viktor-yakubiv** [comment]
I agree, you can get rid out of _PDF*_ prefix as much as possible. It's up to you to decide what should be renamed. I suggest to renamed things that are not strongly tied to PDF.

I would rename the following (but keep original names for ~stroke out items~):
- ~pdf-downloader~
- pdf-enhancement-sidebar
- pdf-highlighter
- pdf-loader (if it's a spinner only, if it does actual loading, keep the PDF)
- pdf-outline-sidebar
- ~pdf-print~
- pdf-recommender
- pdf-thumbnails-sidebar
- pdf-toolbar
- pdf-viewer

Although, it still is up to you to decide because you know the product better. I would not call generic UI parts with pdf-something but everything else is fine.
